fix

diff --git a/gcc15.patch b/gcc15.patch
--- a/gcc15.patch
+++ b/gcc15.patch
@@ -1,14 +1,11 @@
---- scripts/kconfig/lxdialog/check-lxdialog.sh.orig	2026-02-12 22:27:47.161548189 +0300
-+++ scripts/kconfig/lxdialog/check-lxdialog.sh	2026-02-12 22:24:22.884656629 +0300
-@@ -45,9 +45,9 @@
-
- # Check if we can link to ncurses
+--- scripts/kconfig/lxdialog/check-lxdialog.sh.orig	2026-02-27 21:07:21.646281516 +0300
++++ scripts/kconfig/lxdialog/check-lxdialog.sh	2026-02-27 21:07:29.626810122 +0300
+@@ -47,7 +47,7 @@
  check() {
--        $cc -x c - -o $tmp 2>/dev/null <<'EOF'
-+        $cc -x c - -o $tmp 2>&1 <<'EOF'
+         $cc -x c - -o $tmp 2>/dev/null <<'EOF'
  #include CURSES_LOC
 -main() {}
 +int main() {return 0;}
  EOF
  	if [ $? != 0 ]; then
- 	    echo " *** Unable to find the ncurses libraries or the"       1>&2
+ 	   echo " *** Unable to find the ncurses libraries or the"       1>&2
